language: python
dist: xenial
sudo: false

python:
  - '3.8'
  - '3.7'
  - '3.6'
install: pip install --upgrade -e . -r requirements/dev-ward.txt
script: ward

jobs:
  include:
    - name: black
      install: pip install -r requirements/dev-black.txt
      script: black --check .

    - name: pylint
      install: pip install -r requirements/dev-pylint.txt
      script: pylint -E .
