name: run-tests

'on':
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 8 1 * *'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade -r requirements/dev-black.txt
      - run: black --check .

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade -e . -r requirements/dev-pylint.txt
      - run: pylint -E src/*.py
