name: run-tests

'on':
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 8 1 * *'

jobs:
  ward:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          sudo apt-get install -y --no-install-recommends systemd
          pip install --upgrade -e . -r requirements/dev-ward.txt
      - run: ward

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade -r requirements/dev-black.txt
      - run: black --check .

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade -e . -r requirements/dev-pylint.txt
      - run: pylint -E src/*.py
